/**
 * @file 隊長清單.ts
 * @description UI 骨架用的隊長 placeholder 資料，摘自 doc/角色與敵方/角色圖鑑.md。
 * 完整技能數值不在此檔維護，未來正式數值請串接 src/captain/ 下的引擎邏輯。
 */
import type { 隊長資料 } from "../共用型別";

export const 隊長清單: 隊長資料[] = [
  {
    id: "conductor",
    名稱: "Conductor",
    名稱英: "Conductor",
    代號: "C - 指導者",
    代號英: "C - Conductor",
    控制效果: "擊退 (Knockback)",
    控制效果英: "Knockback",
    主動位移技能: "加速",
    主動位移技能英: "Speed Surge",
    週期技能: "狂暴狀態",
    週期技能英: "Berserk State",
    代表色: "#3b5bff",
    一句話設計: "節奏大師，提供小隊爆發性的移動與戰歌激勵能力。",
    一句話設計英: "A rhythm master who drives burst movement and battle-song momentum for the squad.",
  },
  {
    id: "operator",
    名稱: "Operator",
    名稱英: "Operator",
    代號: "O - 操作者",
    代號英: "O - Operator",
    控制效果: "沉默 (Silence)",
    控制效果英: "Silence",
    主動位移技能: "傳送點",
    主動位移技能英: "Blink Mark",
    週期技能: "短暫隱身",
    週期技能英: "Brief Cloak",
    代表色: "#8f8f9c",
    一句話設計: "空間與干擾大師，擅長出其不意的瞬間移動與光學迷彩。",
    一句話設計英: "A master of space and disruption, built for surprise repositioning and optical camouflage.",
  },
  {
    id: "launcher",
    名稱: "Launcher",
    名稱英: "Launcher",
    代號: "L - 投射者",
    代號英: "L - Launcher",
    控制效果: "眩暈 (Stun)",
    控制效果英: "Stun",
    主動位移技能: "鉤索拖曳",
    主動位移技能英: "Grapple Drag",
    週期技能: "引力牽引",
    週期技能英: "Gravity Pull",
    代表色: "#ff8a3b",
    一句話設計: "強襲與開團先鋒，提供遠程牽引與黑洞般的聚怪能力。",
    一句話設計英: "An assault initiator who drags targets in from afar and groups enemies like a living singularity.",
  },
  {
    id: "architect",
    名稱: "Architect",
    名稱英: "Architect",
    代號: "A - 建築師",
    代號英: "A - Architect",
    控制效果: "減慢 (Slow)",
    控制效果英: "Slow",
    主動位移技能: "減速領域",
    主動位移技能英: "Slow Field",
    週期技能: "隱形陷阱",
    週期技能英: "Hidden Trap",
    代表色: "#3bbf6d",
    一句話設計: "陣地戰的核心，提供大範圍的重力控制與陷阱布防。",
    一句話設計英: "The core of positional warfare, shaping space with wide gravity control and trap setups.",
  },
];
